export const icons = [
  { font: "", color: "blue", name: "C", type: /^c$/ },
  { font: "", color: "blue", name: "C++", type: /^cpp$/ },
  { font: "󰌛", color: "green", name: "C#", type: /^cs$/ },
  { font: "", color: "yellow", name: "Javascript", type: /^javascript$/ },
  { font: "", color: "lightblue", name: "Typescript", type: /^typescript$/ },
  { font: "", color: "lightblue", name: "React", type: /^(javascriptreact)|(typescriptreact)$/ },
  { font: "", color: "purple", name: "PHP", type: /^php$/ },
  { font: "", color: "lightblue", name: "Perl", type: /^perl$/ },
  { font: "", color: "yellow", name: "Python", type: /^python$/ },
  { font: "", color: "lightblue", name: "Go", type: /^go$/ },
  { font: "", color: "red", name: "Java", type: /^java$/ },
  { font: "", color: "red", name: "Ruby", type: /^ruby$/ },
  { font: "", color: "lightblue", name: "Lua", type: /^lua$/ },
  { font: "", color: "red", name: "HTML", type: /^html$/ },
  { font: "", color: "lightblue", name: "CSS", type: /^(css)|(less)$/ },
  { font: "", color: "red", name: "Sass", type: /^(sass)|(scss)$/ },
  { font: "", color: "green", name: "Vim", type: /^vim$/ },
  { font: "", color: "green", name: "Shell", type: /^(sh)|(fish)|(zsh)|(terminal)|(prompt)$/ },
  { font: "", color: "red", name: "Git", type: /git/ },
  { font: "", color: "blue", name: "Docker", type: /docker/i },
  { font: "ﬥ", color: "gray", name: "JSON", type: /^json$/ },
  { font: "", color: "gray", name: "Config", type: /^(yaml)|(toml)|(make)|(conf)$/ },
  { font: "󰗀", color: "orange", name: "Xml", type: /^xml$/ },
  { font: "󰆼", color: "yellow", name: "SQL", type: /^(mysql)|(sql)$/ },
  { font: "", color: "lightblue", name: "Markdown", type: /^markdown$/ },
  { font: "󰈙", color: "gray", name: "Text", type: /^text$/ },
  { font: "", color: "red", name: "Quickfix", type: /^qf$/ },
  { font: "󰋗", color: "pink", name: "Help", type: /^help$/ },
  { font: "", color: "gray", name: "File", type: /.*/ },
];

export const notificates = [
  { font: "", kinds: ["echo",  "echomsg", "lua_print", ""]},
  { font: "", kinds: ["quickfix",  "search_count", "search_cmd"]},
  { font: "", kinds: ["wmsg"]},
  { font: "", kinds: ["emsg", "echoerr", "lua_error", "rpc_error"]},
  { font: "", kinds: ["confirm", "confirm_sub"]},
  { font: "󰌑", kinds: ["return_prompt"]},
  { font: "", kinds: ["mode", "command", "list_cmd", "number_prompt", "wildlist"]},
  { font: "", kinds: ["bufwrite"]},
  { font: "", kinds: ["ruler"]},
  { font: "", kinds: ["debug"]},
];
