export const icons = [
  { font: "", color: "blue", name: "C", type: /^c$/ },
  { font: "", color: "blue", name: "C++", type: /^cpp$/ },
  { font: "", color: "yellow", name: "Javascript", type: /^(javascript)|(javascriptreact)$/ },
  { font: "", color: "lightblue", name: "Typescript", type: /^(typescript)|(typescriptreact)$/ },
  { font: "", color: "purple", name: "PHP", type: /^php$/ },
  { font: "", color: "lightblue", name: "Perl", type: /^perl$/ },
  { font: "", color: "yellow", name: "Python", type: /^python$/ },
  { font: "", color: "red", name: "Ruty", type: /^ruby$/ },
  { font: "", color: "lightblue", name: "Lua", type: /^lua$/ },
  { font: "", color: "red", name: "HTML", type: /^html$/ },
  { font: "", color: "lightblue", name: "CSS", type: /^(css)|(scss)|(less)$/ },
  { font: "", color: "green", name: "Vim", type: /^vim$/ },
  { font: "", color: "green", name: "Shell", type: /^(sh)|(zsh)|(terminal)$/ },
  { font: "", color: "red", name: "Git", type: /git/ },
  { font: "", color: "blue", name: "Docker", type: /docker/i },
  { font: "ﬥ", color: "gray", name: "JSON", type: /^json$/ },
  { font: "", color: "gray", name: "Config", type: /^(yaml)|(toml)$/ },
  { font: "", color: "yellow", name: "SQL", type: /^sql$/ },
  { font: "", color: "red", name: "Quickfix", type: /^qf$/ },
  { font: "", color: "pink", name: "Help", type: /^help$/ },
  { font: "", color: "gray", name: "File", type: /.*/ },
];

export const notificates = [
  { font: "", kinds: ["echo",  "echomsg", ""]},
  { font: "", kinds: ["quickfix",  "search_count"]},
  { font: "", kinds: ["wmsg"]},
  { font: "", kinds: ["emsg", "echoerr", "lua_error", "rpc_error"]},
  { font: "", kinds: ["confirm", "confirm_sub"]},
  { font: "", kinds: ["return_prompt"]},
  { font: "", kinds: ["mode", "command"]},
  { font: "", kinds: ["ruler"]},
  { font: "", kinds: ["debug"]},
];
